version: '3.1'

services:

  nginx:
      image: nginx:latest
      ports:
          - '7000:80'
      volumes:
          - ./nginx:/etc/nginx/conf.d
          - ./logs/nginx:/var/log/nginx
          - ./drupal:/var/www/html
      links:
          - drupal
      restart: always

  drupal:
      image: drupal:8.6.3-fpm-alpine
      volumes:
          - ./drupal:/var/www/html
          - ./phpconfig/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      restart: always